{
  config,
  lib,
  pkgs,
  osConfig ? null,
  ...
}:
let
  pins = import ./pins.nix;
  claude-code-flake = builtins.getFlake "github:${pins.claude-code-nix.owner}/${pins.claude-code-nix.repo}/${pins.claude-code-nix.rev}";
  agentSkillsFlake = builtins.getFlake "github:${pins.agent-skills-nix.owner}/${pins.agent-skills-nix.repo}/${pins.agent-skills-nix.rev}";

  resurrectSrc = builtins.fetchTarball "https://github.com/${pins.resurrect-wezterm.owner}/${pins.resurrect-wezterm.repo}/archive/${pins.resurrect-wezterm.rev}.tar.gz";

  custom = import ./pkgs { inherit pkgs; };

in
{
  imports = [
    agentSkillsFlake.homeManagerModules.default
    ./modules/packages.nix
    ./modules/ai/claude-code.nix
    ./modules/ai/antigravity.nix
    ./modules/ai/herdr.nix
    ./modules/ai/skills.nix
    ./pin-check.nix
    ./g535-audio.nix
  ];

  # --- Identity -------------------------------------------------------------
  home.username = "elliancarlos";
  home.homeDirectory = "/home/elliancarlos";
  home.stateVersion = "25.05";

  nixpkgs.overlays = [ claude-code-flake.overlays.default ];


  xdg.configFile = {
    "hypr".source = ../hypr;

    "wezterm" = {
      source = ../wezterm;
      recursive = true;
    };

    "wezterm/nix-paths.lua".text = ''
      -- Generated by home-manager (see home.nix). Do not edit.
      return {
        resurrect = "${resurrectSrc}",
      }
    '';

    "kitty".source = ../kitty;
    "waybar".source = ../waybar;
    "bottom".source = ../bottom;
    # recursive = true (same reason as wezterm above): herdr writes runtime state (socket/log) into this dir, so it must stay real and writable, not a whole-dir symlink into the read-only store.
    "herdr" = {
      source = ../herdr;
      recursive = true;
    };
    "nvim".source = ../nvim;
    "wofi".source = ../wofi;
    "neofetch".source = ../neofetch;
    "wallpapers".source = ../wallpapers;
    "background".source = ../background;
  };

  home.pointerCursor = {
    gtk.enable = true;
    # x11.enable = true;
    package = pkgs.bibata-cursors;
    name = "Bibata-Modern-Classic";
    size = 24;
  };

  gtk = {
    enable = true;
    theme = {
      package = pkgs.catppuccin-gtk;
      name = "catppuccin-mocha-lavender-standard";
    };
    cursorTheme = {
      package = pkgs.bibata-cursors;
      name = "Bibata-Modern-Classic";
    };
    iconTheme = {
      package = pkgs.papirus-icon-theme;
      name = "Papirus-Dark";
    };
  };

  # --- Japanese input (fcitx5 + Mozc) -----------------------------------------
  # Toggle with SUPER+I (hyprland.conf, via `fcitx5-remote -t`) or by
  # clicking the language module in waybar. fcitx5's own TriggerKeys are
  # cleared below so it never grabs a hotkey on its own -- this is what
  # keeps Ctrl+Space free for nvim's completion menu.
  i18n.inputMethod = {
    enable = true;
    type = "fcitx5";
    fcitx5 = {
      # Registers fcitx5 as a Wayland input-method (input-method-v2), so
      # Wayland-native apps (wezterm, GTK4/Qt6 apps) get IME support without
      # relying on the GTK_IM_MODULE/QT_IM_MODULE env vars below.
      waylandFrontend = true;
      addons = with pkgs; [
        fcitx5-mozc
        fcitx5-gtk
      ];
      settings = {
        globalOptions."Hotkey" = {
          TriggerKeys = "";
          AltTriggerKeys = "";
          EnumerateWithTriggerKeys = "False";
        };
        inputMethod = {
          "Groups/0" = {
            Name = "Default";
            "Default Layout" = "us";
            DefaultIM = "keyboard-us";
          };
          # Blank Layout inherits kb_layout/kb_variant from hyprland.conf
          # (us intl), so normal typing is unaffected when Mozc is off.
          "Groups/0/Items/0" = {
            Name = "keyboard-us";
            Layout = "";
          };
          "Groups/0/Items/1" = {
            Name = "mozc";
            Layout = "";
          };
          GroupOrder."0" = "Default";
        };
      };
    };
  };

  # --- Dotfiles ---------------------------------------------------------------
  home.file = {
    ".p10k.zsh".source = ./p10k.zsh;
    ".ticker.yaml".source = ../.ticker.yaml;

    # --- Compose-key accents (replaces the old GTK "cedilla" module) ---
    # "%L" pulls in the system's default Compose table for the current
    # locale, which already defines ç, é, ã, õ, ü, etc. The Menu key is set
    # as the Compose key in hyprland.conf (kb_options = compose:menu).
    ".XCompose".text = ''
      include "%L"
    '';

  };

  # --- Session variables ------------------------------------------------------
  # GTK_IM_MODULE / QT_IM_MODULE / XMODIFIERS / SDL_IM_MODULE are no longer
  # set here: i18n.inputMethod.fcitx5.sessionVariables (below) sets them to
  # "fcitx" itself. Cedilla/accent input moved from the old GTK-only
  # "cedilla" module to a Compose key (see kb_options in hyprland.conf and
  # ~/.XCompose below).
  home.sessionVariables = { };

  programs.fzf = {
    enable = true;
    enableZshIntegration = true;
  };

  programs.zsh = {
    enable = true;

    localVariables = {
      ZSH_DISABLE_COMPFIX = "true";
    };

    shellAliases = {
      # --- Files & editor ---------------------------------------------------
      la = "ls -la";
      ll = "ls -l";
      v = "nvim";

      # --- NixOS ------------------------------------------------------------
      # Copy the local config to /etc/nixos, then rebuild
      update = "sudo cp -r ~/Projects/.dotfiles/nixos/* /etc/nixos/ && sudo nixos-rebuild switch";
      # Quick garbage collection
      gc = "nix-collect-garbage -d && sudo nix-collect-garbage -d";

      # --- System history (atop) --------------------------------------------
      # atopsar summaries read today's log automatically.
      atop-mem = "atopsar -m"; # memory + swap over time
      atop-swap = "atopsar -s"; # swap pressure
      atop-cpu = "atopsar -c"; # cpu utilisation
      atop-procs = "atopsar -G"; # top memory-consuming processes
      atop-cpuprocs = "atopsar -p"; # top cpu-consuming processes
      # Interactive replay. Inside atop: t/T step through samples, m sorts by
      # memory, c shows full command lines, q quits. For any other day:
      #   atop -r /var/log/atop/atop_20260807 -b 15:10
      atop-today = "atop -r /var/log/atop/atop_$(date +%Y%m%d)";
      atop-yday = "atop -r /var/log/atop/atop_$(date -d yesterday +%Y%m%d)";
      # What the kernel or earlyoom killed this boot
      oom-log = "journalctl -b | grep -iE 'oom|killed process|earlyoom'";

      # --- Audio ------------------------------------------------------------
      # Change default sink
      audio-headset = "audio-to alsa_output.usb-Logitech_G535_Wireless_Gaming_Headset-00.analog-stereo";
      audio-hdmi = "audio-to alsa_output.pci-0000_03_00.1.hdmi-stereo-extra1";
      audio-combine = "audio-to combine-sink";

      caffeinate = "systemd-inhibit --what=idle:sleep:handle-lid-switch --why='coding-through-the-phone' sleep infinity";

    };

    autosuggestion.enable = true;
    enableCompletion = true;
    syntaxHighlighting.enable = true;

    initContent = ''
      if [[ -r "''${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-''${(%):-%n}.zsh" ]]; then
        source "''${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-''${(%):-%n}.zsh"
      fi
    '';

    initExtra = ''
      [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

      # --- Antigravity CLI (agy): API-key auth, no interactive login -------
      export GEMINI_API_KEY="$(${pkgs.pass}/bin/pass show gemini 2>/dev/null)"

      audio-to() {
        pactl set-default-sink "$1"
        for i in $(pactl list short sink-inputs | cut -f1); do
          pactl move-sink-input "$i" "$1" 2>/dev/null
        done
      }
    '';

    oh-my-zsh = {
      enable = true;

      plugins = [
        "git"
        "z"
        "copyfile"
        "history"
        "dirhistory"
      ];

      theme = "";
    };

    plugins = [
      {
        name = "powerlevel10k";
        src = pkgs.zsh-powerlevel10k;
        file = "share/zsh-powerlevel10k/powerlevel10k.zsh-theme";
      }
      {
        name = "zsh-completions";
        src = pkgs.fetchFromGitHub {
          owner = "zsh-users";
          repo = "zsh-completions";
          rev = "0.35.0";
          hash = "sha256-GFHlZjIHUWwyeVoCpszgn4AmLPSSE8UVNfRmisnhkpg=";
        };
      }
      {
        name = "zsh-syntax-highlighting";
        src = pkgs.fetchFromGitHub {
          owner = "zsh-users";
          repo = "zsh-syntax-highlighting";
          rev = "0.8.0";
          hash = "sha256-iJdWopZwHpSyYl5/FQXEW7gl/SrKaYDEtTH9cGP7iPo=";
        };
      }
    ];
  };

  programs.wofi = {
    enable = true;
  };

  services.mako = {
    enable = true;
  };

  # Vicinae launcher daemon (bound to SUPER + SPACE in hyprland.conf).
  # No home-manager module upstream yet, so the unit is declared by hand.
  systemd.user.services.vicinae = {
    Unit = {
      Description = "Vicinae launcher daemon";
      Documentation = "https://docs.vicinae.com";
      After = [ "graphical-session.target" ];
      PartOf = [ "graphical-session.target" ];
      Requires = [ "dbus.socket" ];
    };
    Service = {
      Type = "simple";
      ExecStart = "${pkgs.vicinae}/bin/vicinae server";
      ExecReload = "${pkgs.coreutils}/bin/kill -HUP $MAINPID";
      Restart = "on-failure";
      RestartSec = 3;
      KillMode = "process";
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };

  programs.neovim = {
    enable = true;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;

    extraPackages = with pkgs; [
      gcc
      gnumake
      unzip
      wget
      curl
      tree-sitter

      fzf
      trash-cli
      diffutils
      ghostscript
      tectonic

      lua-language-server
      stylua

      nil
      nixpkgs-fmt

      nodejs_22

      vscode-langservers-extracted

      prettier
      prettierd
      eslint_d
      biome
      stylelint

      pyright
      black

      rust-analyzer
      rustfmt

      kotlin-language-server
      ktlint

      shfmt
      shellcheck

      ast-grep
      detekt
      nimlangserver

      # --- C / C++ (also covers linux-kernel work) ---
      clang-tools # clangd (LSP) + clang-format (formatter)
    ];
  };

  programs.neomutt = {
    enable = true;
    vimKeys = true;
    sort = "threads";
    extraConfig = ''
      set timeout = 3;
      set mail_check = 60;
      set collapse_all = yes;
      set use_threads = yes;
      set sort = "reverse-last-date-received";
      set delete = ask-yes;
    '';
  };

  accounts.email.accounts = import ./email.nix { inherit pkgs; };

  programs.mbsync.enable = true;

  programs.gpg.enable = true;

  services.gpg-agent = {
    enable = true;
    pinentry.package = pkgs.pinentry-curses;
  };

  # --- Home Manager itself ----------------------------------------------------
  programs.home-manager.enable = true;
}
