# Symlinks the app config directories in .config/ into place.
{ config, ... }:
let
  pins = import ../../pins.nix;
  resurrectSrc = builtins.fetchTarball "https://github.com/${pins.resurrect-wezterm.owner}/${pins.resurrect-wezterm.repo}/archive/${pins.resurrect-wezterm.rev}.tar.gz";
in
{
  xdg.configFile = {
    "hypr".source = ../../../hypr;

    "wezterm" = {
      source = ../../../wezterm;
      recursive = true;
    };

    "wezterm/nix-paths.lua".text = ''
      -- Generated by home-manager (see modules/desktop/dotfiles.nix). Do not edit.
      return {
        resurrect = "${resurrectSrc}",
      }
    '';

    "kitty".source = ../../../kitty;
    "waybar".source = ../../../waybar;
    "bottom".source = ../../../bottom;
    # recursive = true (same reason as wezterm above): herdr writes runtime state (socket/log) into this dir, so it must stay real and writable, not a whole-dir symlink into the read-only store.
    "herdr" = {
      source = ../../../herdr;
      recursive = true;
    };
    # An out-of-store symlink, not a store copy: lazy.nvim writes lazy-lock.json
    # (plugin commit pins) back into this directory when installing/updating
    # plugins, which the read-only Nix store wouldn't allow.
    "nvim".source = config.lib.file.mkOutOfStoreSymlink ../../../nvim;
    "wofi".source = ../../../wofi;
    "neofetch".source = ../../../neofetch;
    "wallpapers".source = ../../../wallpapers;
    "background".source = ../../../background;
  };
}
