# Symlinks the app config directories in .config/ into place.
{ config, ... }:
let
  pins = import ../../pins.nix;
  resurrectSrc = builtins.fetchTarball "https://github.com/${pins.resurrect-wezterm.owner}/${pins.resurrect-wezterm.repo}/archive/${pins.resurrect-wezterm.rev}.tar.gz";
in
{
  xdg.configFile = {
    "hypr".source = ../../../hypr;

    "wezterm" = {
      source = ../../../wezterm;
      recursive = true;
    };

    "wezterm/nix-paths.lua".text = ''
      -- Generated by home-manager (see modules/desktop/dotfiles.nix). Do not edit.
      return {
        resurrect = "${resurrectSrc}",
      }
    '';

    "kitty".source = ../../../kitty;
    "waybar".source = ../../../waybar;
    "bottom".source = ../../../bottom;
    # Only config.toml is tracked here; herdr writes everything else in this dir
    # itself at runtime (logs, sockets, session.json, plugins/...), and also
    # rewrites config.toml in place during onboarding -- so it needs an
    # out-of-store symlink (same reason as nvim below), not a store copy.
    "herdr/config.toml".source = config.lib.file.mkOutOfStoreSymlink ../../../herdr/config.toml;
    # An out-of-store symlink, not a store copy: lazy.nvim writes lazy-lock.json
    # (plugin commit pins) back into this directory when installing/updating
    # plugins, which the read-only Nix store wouldn't allow.
    "nvim".source = config.lib.file.mkOutOfStoreSymlink ../../../nvim;
    "wofi".source = ../../../wofi;
    "neofetch".source = ../../../neofetch;
    "wallpapers".source = ../../../wallpapers;
    "background".source = ../../../background;
  };
}
